/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class anchor_caps_ {
  public final static anchor_caps_ anchor_caps_storable = new anchor_caps_("anchor_caps_storable", StereoKitJNI.anchor_caps_storable_get());
  public final static anchor_caps_ anchor_caps_stability = new anchor_caps_("anchor_caps_stability", StereoKitJNI.anchor_caps_stability_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static anchor_caps_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + anchor_caps_.class + " with value " + swigValue);
  }

  private anchor_caps_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private anchor_caps_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private anchor_caps_(String swigName, anchor_caps_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static anchor_caps_[] swigValues = { anchor_caps_storable, anchor_caps_stability };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

