/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class app_focus_ {
  public final static app_focus_ app_focus_active = new app_focus_("app_focus_active");
  public final static app_focus_ app_focus_background = new app_focus_("app_focus_background");
  public final static app_focus_ app_focus_hidden = new app_focus_("app_focus_hidden");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static app_focus_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + app_focus_.class + " with value " + swigValue);
  }

  private app_focus_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private app_focus_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private app_focus_(String swigName, app_focus_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static app_focus_[] swigValues = { app_focus_active, app_focus_background, app_focus_hidden };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

