/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class asset_state_ {
  public final static asset_state_ asset_state_none = new asset_state_("asset_state_none");
  public final static asset_state_ asset_state_loading = new asset_state_("asset_state_loading");
  public final static asset_state_ asset_state_loaded = new asset_state_("asset_state_loaded");
  public final static asset_state_ asset_state_failed = new asset_state_("asset_state_failed");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static asset_state_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + asset_state_.class + " with value " + swigValue);
  }

  private asset_state_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private asset_state_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private asset_state_(String swigName, asset_state_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static asset_state_[] swigValues = { asset_state_none, asset_state_loading, asset_state_loaded, asset_state_failed };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

