/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class backend_platform_ {
  public final static backend_platform_ backend_platform_win32 = new backend_platform_("backend_platform_win32");
  public final static backend_platform_ backend_platform_uwp = new backend_platform_("backend_platform_uwp");
  public final static backend_platform_ backend_platform_linux = new backend_platform_("backend_platform_linux");
  public final static backend_platform_ backend_platform_android = new backend_platform_("backend_platform_android");
  public final static backend_platform_ backend_platform_web = new backend_platform_("backend_platform_web");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static backend_platform_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + backend_platform_.class + " with value " + swigValue);
  }

  private backend_platform_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private backend_platform_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private backend_platform_(String swigName, backend_platform_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static backend_platform_[] swigValues = { backend_platform_win32, backend_platform_uwp, backend_platform_linux, backend_platform_android, backend_platform_web };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

