/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class backend_graphics_ {
  public final static backend_graphics_ backend_graphics_none = new backend_graphics_("backend_graphics_none");
  public final static backend_graphics_ backend_graphics_d3d11 = new backend_graphics_("backend_graphics_d3d11");
  public final static backend_graphics_ backend_graphics_opengl_glx = new backend_graphics_("backend_graphics_opengl_glx");
  public final static backend_graphics_ backend_graphics_opengl_wgl = new backend_graphics_("backend_graphics_opengl_wgl");
  public final static backend_graphics_ backend_graphics_opengles_egl = new backend_graphics_("backend_graphics_opengles_egl");
  public final static backend_graphics_ backend_graphics_webgl = new backend_graphics_("backend_graphics_webgl");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static backend_graphics_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + backend_graphics_.class + " with value " + swigValue);
  }

  private backend_graphics_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private backend_graphics_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private backend_graphics_(String swigName, backend_graphics_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static backend_graphics_[] swigValues = { backend_graphics_none, backend_graphics_d3d11, backend_graphics_opengl_glx, backend_graphics_opengl_wgl, backend_graphics_opengles_egl, backend_graphics_webgl };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

