/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class backend_xr_type_ {
  public final static backend_xr_type_ backend_xr_type_none = new backend_xr_type_("backend_xr_type_none");
  public final static backend_xr_type_ backend_xr_type_simulator = new backend_xr_type_("backend_xr_type_simulator");
  public final static backend_xr_type_ backend_xr_type_openxr = new backend_xr_type_("backend_xr_type_openxr");
  public final static backend_xr_type_ backend_xr_type_webxr = new backend_xr_type_("backend_xr_type_webxr");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static backend_xr_type_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + backend_xr_type_.class + " with value " + swigValue);
  }

  private backend_xr_type_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private backend_xr_type_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private backend_xr_type_(String swigName, backend_xr_type_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static backend_xr_type_[] swigValues = { backend_xr_type_none, backend_xr_type_simulator, backend_xr_type_openxr, backend_xr_type_webxr };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

