/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class color32 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected color32(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(color32 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(color32 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_color32(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(short value) {
    StereoKitJNI.color32_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return StereoKitJNI.color32_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    StereoKitJNI.color32_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return StereoKitJNI.color32_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    StereoKitJNI.color32_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return StereoKitJNI.color32_b_get(swigCPtr, this);
  }

  public void setA(short value) {
    StereoKitJNI.color32_a_set(swigCPtr, this, value);
  }

  public short getA() {
    return StereoKitJNI.color32_a_get(swigCPtr, this);
  }

  public color32() {
    this(StereoKitJNI.new_color32(), true);
  }

}
