/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class device_tracking_ {
  public final static device_tracking_ device_tracking_none = new device_tracking_("device_tracking_none", StereoKitJNI.device_tracking_none_get());
  public final static device_tracking_ device_tracking_3dof = new device_tracking_("device_tracking_3dof");
  public final static device_tracking_ device_tracking_6dof = new device_tracking_("device_tracking_6dof");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static device_tracking_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + device_tracking_.class + " with value " + swigValue);
  }

  private device_tracking_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private device_tracking_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private device_tracking_(String swigName, device_tracking_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static device_tracking_[] swigValues = { device_tracking_none, device_tracking_3dof, device_tracking_6dof };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

