/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class display_type_ {
  public final static display_type_ display_type_none = new display_type_("display_type_none");
  public final static display_type_ display_type_stereo = new display_type_("display_type_stereo");
  public final static display_type_ display_type_flatscreen = new display_type_("display_type_flatscreen");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static display_type_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + display_type_.class + " with value " + swigValue);
  }

  private display_type_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private display_type_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private display_type_(String swigName, display_type_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static display_type_[] swigValues = { display_type_none, display_type_stereo, display_type_flatscreen };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

