/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class file_filter_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected file_filter_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(file_filter_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(file_filter_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_file_filter_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExt(String value) {
    StereoKitJNI.file_filter_t_ext_set(swigCPtr, this, value);
  }

  public String getExt() {
    return StereoKitJNI.file_filter_t_ext_get(swigCPtr, this);
  }

  public file_filter_t() {
    this(StereoKitJNI.new_file_filter_t(), true);
  }

}
