/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class gradient_key_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected gradient_key_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gradient_key_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(gradient_key_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_gradient_key_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setColor(color128 value) {
    StereoKitJNI.gradient_key_t_color_set(swigCPtr, this, color128.getCPtr(value), value);
  }

  public color128 getColor() {
    long cPtr = StereoKitJNI.gradient_key_t_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new color128(cPtr, false);
  }

  public void setPosition(float value) {
    StereoKitJNI.gradient_key_t_position_set(swigCPtr, this, value);
  }

  public float getPosition() {
    return StereoKitJNI.gradient_key_t_position_get(swigCPtr, this);
  }

  public gradient_key_t() {
    this(StereoKitJNI.new_gradient_key_t(), true);
  }

}
