/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class hand_joint_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected hand_joint_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(hand_joint_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(hand_joint_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_hand_joint_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPosition(vec3 value) {
    StereoKitJNI.hand_joint_t_position_set(swigCPtr, this, vec3.getCPtr(value), value);
  }

  public vec3 getPosition() {
    long cPtr = StereoKitJNI.hand_joint_t_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vec3(cPtr, false);
  }

  public void setOrientation(SWIGTYPE_p_quat value) {
    StereoKitJNI.hand_joint_t_orientation_set(swigCPtr, this, SWIGTYPE_p_quat.getCPtr(value));
  }

  public SWIGTYPE_p_quat getOrientation() {
    return new SWIGTYPE_p_quat(StereoKitJNI.hand_joint_t_orientation_get(swigCPtr, this), true);
  }

  public void setRadius(float value) {
    StereoKitJNI.hand_joint_t_radius_set(swigCPtr, this, value);
  }

  public float getRadius() {
    return StereoKitJNI.hand_joint_t_radius_get(swigCPtr, this);
  }

  public hand_joint_t() {
    this(StereoKitJNI.new_hand_joint_t(), true);
  }

}
