/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class hand_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected hand_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(hand_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(hand_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_hand_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFingers(SWIGTYPE_p_a_5__hand_joint_t value) {
    StereoKitJNI.hand_t_fingers_set(swigCPtr, this, SWIGTYPE_p_a_5__hand_joint_t.getCPtr(value));
  }

  public SWIGTYPE_p_a_5__hand_joint_t getFingers() {
    long cPtr = StereoKitJNI.hand_t_fingers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_5__hand_joint_t(cPtr, false);
  }

  public void setWrist(pose_t value) {
    StereoKitJNI.hand_t_wrist_set(swigCPtr, this, pose_t.getCPtr(value), value);
  }

  public pose_t getWrist() {
    long cPtr = StereoKitJNI.hand_t_wrist_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pose_t(cPtr, false);
  }

  public void setPalm(pose_t value) {
    StereoKitJNI.hand_t_palm_set(swigCPtr, this, pose_t.getCPtr(value), value);
  }

  public pose_t getPalm() {
    long cPtr = StereoKitJNI.hand_t_palm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pose_t(cPtr, false);
  }

  public void setPinch_pt(vec3 value) {
    StereoKitJNI.hand_t_pinch_pt_set(swigCPtr, this, vec3.getCPtr(value), value);
  }

  public vec3 getPinch_pt() {
    long cPtr = StereoKitJNI.hand_t_pinch_pt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vec3(cPtr, false);
  }

  public void setHandedness(handed_ value) {
    StereoKitJNI.hand_t_handedness_set(swigCPtr, this, value.swigValue());
  }

  public handed_ getHandedness() {
    return handed_.swigToEnum(StereoKitJNI.hand_t_handedness_get(swigCPtr, this));
  }

  public void setPinch_activation(float value) {
    StereoKitJNI.hand_t_pinch_activation_set(swigCPtr, this, value);
  }

  public float getPinch_activation() {
    return StereoKitJNI.hand_t_pinch_activation_get(swigCPtr, this);
  }

  public void setGrip_activation(float value) {
    StereoKitJNI.hand_t_grip_activation_set(swigCPtr, this, value);
  }

  public float getGrip_activation() {
    return StereoKitJNI.hand_t_grip_activation_get(swigCPtr, this);
  }

  public hand_t() {
    this(StereoKitJNI.new_hand_t(), true);
  }

}
