/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class picker_mode_ {
  public final static picker_mode_ picker_mode_open = new picker_mode_("picker_mode_open");
  public final static picker_mode_ picker_mode_save = new picker_mode_("picker_mode_save");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static picker_mode_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + picker_mode_.class + " with value " + swigValue);
  }

  private picker_mode_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private picker_mode_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private picker_mode_(String swigName, picker_mode_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static picker_mode_[] swigValues = { picker_mode_open, picker_mode_save };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

