/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class quat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected quat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(quat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(quat obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_quat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    StereoKitJNI.quat_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return StereoKitJNI.quat_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    StereoKitJNI.quat_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return StereoKitJNI.quat_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    StereoKitJNI.quat_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return StereoKitJNI.quat_z_get(swigCPtr, this);
  }

  public void setW(float value) {
    StereoKitJNI.quat_w_set(swigCPtr, this, value);
  }

  public float getW() {
    return StereoKitJNI.quat_w_get(swigCPtr, this);
  }

  public quat() {
    this(StereoKitJNI.new_quat(), true);
  }

}
