/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class ray_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ray_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ray_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ray_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_ray_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPos(vec3 value) {
    StereoKitJNI.ray_t_pos_set(swigCPtr, this, vec3.getCPtr(value), value);
  }

  public vec3 getPos() {
    long cPtr = StereoKitJNI.ray_t_pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vec3(cPtr, false);
  }

  public void setDir(vec3 value) {
    StereoKitJNI.ray_t_dir_set(swigCPtr, this, vec3.getCPtr(value), value);
  }

  public vec3 getDir() {
    long cPtr = StereoKitJNI.ray_t_dir_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vec3(cPtr, false);
  }

  public ray_t() {
    this(StereoKitJNI.new_ray_t(), true);
  }

}
