/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class rect_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected rect_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rect_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(rect_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_rect_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    StereoKitJNI.rect_t_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return StereoKitJNI.rect_t_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    StereoKitJNI.rect_t_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return StereoKitJNI.rect_t_y_get(swigCPtr, this);
  }

  public void setW(float value) {
    StereoKitJNI.rect_t_w_set(swigCPtr, this, value);
  }

  public float getW() {
    return StereoKitJNI.rect_t_w_get(swigCPtr, this);
  }

  public void setH(float value) {
    StereoKitJNI.rect_t_h_set(swigCPtr, this, value);
  }

  public float getH() {
    return StereoKitJNI.rect_t_h_get(swigCPtr, this);
  }

  public rect_t() {
    this(StereoKitJNI.new_rect_t(), true);
  }

}
