/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class render_layer_ {
  public final static render_layer_ render_layer_0 = new render_layer_("render_layer_0", StereoKitJNI.render_layer_0_get());
  public final static render_layer_ render_layer_1 = new render_layer_("render_layer_1", StereoKitJNI.render_layer_1_get());
  public final static render_layer_ render_layer_2 = new render_layer_("render_layer_2", StereoKitJNI.render_layer_2_get());
  public final static render_layer_ render_layer_all = new render_layer_("render_layer_all", StereoKitJNI.render_layer_all_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static render_layer_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + render_layer_.class + " with value " + swigValue);
  }

  private render_layer_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private render_layer_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private render_layer_(String swigName, render_layer_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static render_layer_[] swigValues = { render_layer_0, render_layer_1, render_layer_2, render_layer_all };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

