/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class sh_light_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sh_light_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sh_light_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(sh_light_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_sh_light_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDir_to(vec3 value) {
    StereoKitJNI.sh_light_t_dir_to_set(swigCPtr, this, vec3.getCPtr(value), value);
  }

  public vec3 getDir_to() {
    long cPtr = StereoKitJNI.sh_light_t_dir_to_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vec3(cPtr, false);
  }

  public void setColor(color128 value) {
    StereoKitJNI.sh_light_t_color_set(swigCPtr, this, color128.getCPtr(value), value);
  }

  public color128 getColor() {
    long cPtr = StereoKitJNI.sh_light_t_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new color128(cPtr, false);
  }

  public sh_light_t() {
    this(StereoKitJNI.new_sh_light_t(), true);
  }

}
