/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class sound_inst_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sound_inst_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sound_inst_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(sound_inst_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_sound_inst_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_id(int value) {
    StereoKitJNI.sound_inst_t__id_set(swigCPtr, this, value);
  }

  public int get_id() {
    return StereoKitJNI.sound_inst_t__id_get(swigCPtr, this);
  }

  public void set_slot(short value) {
    StereoKitJNI.sound_inst_t__slot_set(swigCPtr, this, value);
  }

  public short get_slot() {
    return StereoKitJNI.sound_inst_t__slot_get(swigCPtr, this);
  }

  public sound_inst_t() {
    this(StereoKitJNI.new_sound_inst_t(), true);
  }

}
