/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class StereoKitJNI {
  public final static native void vec2_x_set(long jarg1, vec2 jarg1_, float jarg2);
  public final static native float vec2_x_get(long jarg1, vec2 jarg1_);
  public final static native void vec2_y_set(long jarg1, vec2 jarg1_, float jarg2);
  public final static native float vec2_y_get(long jarg1, vec2 jarg1_);
  public final static native long new_vec2();
  public final static native void delete_vec2(long jarg1);
  public final static native void vec3_x_set(long jarg1, vec3 jarg1_, float jarg2);
  public final static native float vec3_x_get(long jarg1, vec3 jarg1_);
  public final static native void vec3_y_set(long jarg1, vec3 jarg1_, float jarg2);
  public final static native float vec3_y_get(long jarg1, vec3 jarg1_);
  public final static native void vec3_z_set(long jarg1, vec3 jarg1_, float jarg2);
  public final static native float vec3_z_get(long jarg1, vec3 jarg1_);
  public final static native long new_vec3();
  public final static native void delete_vec3(long jarg1);
  public final static native void vec4_x_set(long jarg1, vec4 jarg1_, float jarg2);
  public final static native float vec4_x_get(long jarg1, vec4 jarg1_);
  public final static native void vec4_y_set(long jarg1, vec4 jarg1_, float jarg2);
  public final static native float vec4_y_get(long jarg1, vec4 jarg1_);
  public final static native void vec4_z_set(long jarg1, vec4 jarg1_, float jarg2);
  public final static native float vec4_z_get(long jarg1, vec4 jarg1_);
  public final static native void vec4_w_set(long jarg1, vec4 jarg1_, float jarg2);
  public final static native float vec4_w_get(long jarg1, vec4 jarg1_);
  public final static native long new_vec4();
  public final static native void delete_vec4(long jarg1);
  public final static native void quat_x_set(long jarg1, quat jarg1_, float jarg2);
  public final static native float quat_x_get(long jarg1, quat jarg1_);
  public final static native void quat_y_set(long jarg1, quat jarg1_, float jarg2);
  public final static native float quat_y_get(long jarg1, quat jarg1_);
  public final static native void quat_z_set(long jarg1, quat jarg1_, float jarg2);
  public final static native float quat_z_get(long jarg1, quat jarg1_);
  public final static native void quat_w_set(long jarg1, quat jarg1_, float jarg2);
  public final static native float quat_w_get(long jarg1, quat jarg1_);
  public final static native long new_quat();
  public final static native void delete_quat(long jarg1);
  public final static native void matrix_row_set(long jarg1, matrix jarg1_, long jarg2, vec4 jarg2_);
  public final static native long matrix_row_get(long jarg1, matrix jarg1_);
  public final static native void matrix_m_set(long jarg1, matrix jarg1_, long jarg2);
  public final static native long matrix_m_get(long jarg1, matrix jarg1_);
  public final static native long new_matrix(float jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7, float jarg8, float jarg9, float jarg10, float jarg11, float jarg12, float jarg13, float jarg14, float jarg15, float jarg16);
  public final static native void delete_matrix(long jarg1);
  public final static native void pose_t_position_set(long jarg1, pose_t jarg1_, long jarg2, vec3 jarg2_);
  public final static native long pose_t_position_get(long jarg1, pose_t jarg1_);
  public final static native void pose_t_orientation_set(long jarg1, pose_t jarg1_, long jarg2, quat jarg2_);
  public final static native long pose_t_orientation_get(long jarg1, pose_t jarg1_);
  public final static native long new_pose_t();
  public final static native void delete_pose_t(long jarg1);
  public final static native void ray_t_pos_set(long jarg1, ray_t jarg1_, long jarg2, vec3 jarg2_);
  public final static native long ray_t_pos_get(long jarg1, ray_t jarg1_);
  public final static native void ray_t_dir_set(long jarg1, ray_t jarg1_, long jarg2, vec3 jarg2_);
  public final static native long ray_t_dir_get(long jarg1, ray_t jarg1_);
  public final static native long new_ray_t();
  public final static native void delete_ray_t(long jarg1);

  static {
    try {
        System.loadLibrary("stereokit-bindings");
    } catch (UnsatisfiedLinkError e) {
        System.err.println("Native code library failed to load. \n" + e);
        System.exit(1);
    }
  }

}
