/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class test_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected test_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(test_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(test_struct obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stereokitJNI.delete_test_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDummy(int value) {
    stereokitJNI.test_struct_dummy_set(swigCPtr, this, value);
  }

  public int getDummy() {
    return stereokitJNI.test_struct_dummy_get(swigCPtr, this);
  }

  public test_struct() {
    this(stereokitJNI.new_test_struct(), true);
  }

}
