/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public final class text_context_ {
  public final static text_context_ text_context_text = new text_context_("text_context_text", StereoKitJNI.text_context_text_get());
  public final static text_context_ text_context_number = new text_context_("text_context_number", StereoKitJNI.text_context_number_get());
  public final static text_context_ text_context_uri = new text_context_("text_context_uri", StereoKitJNI.text_context_uri_get());
  public final static text_context_ text_context_password = new text_context_("text_context_password", StereoKitJNI.text_context_password_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static text_context_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + text_context_.class + " with value " + swigValue);
  }

  private text_context_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private text_context_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private text_context_(String swigName, text_context_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static text_context_[] swigValues = { text_context_text, text_context_number, text_context_uri, text_context_password };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

