/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class ui_settings_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ui_settings_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ui_settings_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ui_settings_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_ui_settings_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMargin(float value) {
    StereoKitJNI.ui_settings_t_margin_set(swigCPtr, this, value);
  }

  public float getMargin() {
    return StereoKitJNI.ui_settings_t_margin_get(swigCPtr, this);
  }

  public void setPadding(float value) {
    StereoKitJNI.ui_settings_t_padding_set(swigCPtr, this, value);
  }

  public float getPadding() {
    return StereoKitJNI.ui_settings_t_padding_get(swigCPtr, this);
  }

  public void setGutter(float value) {
    StereoKitJNI.ui_settings_t_gutter_set(swigCPtr, this, value);
  }

  public float getGutter() {
    return StereoKitJNI.ui_settings_t_gutter_get(swigCPtr, this);
  }

  public void setDepth(float value) {
    StereoKitJNI.ui_settings_t_depth_set(swigCPtr, this, value);
  }

  public float getDepth() {
    return StereoKitJNI.ui_settings_t_depth_get(swigCPtr, this);
  }

  public void setRounding(float value) {
    StereoKitJNI.ui_settings_t_rounding_set(swigCPtr, this, value);
  }

  public float getRounding() {
    return StereoKitJNI.ui_settings_t_rounding_get(swigCPtr, this);
  }

  public void setBackplate_depth(float value) {
    StereoKitJNI.ui_settings_t_backplate_depth_set(swigCPtr, this, value);
  }

  public float getBackplate_depth() {
    return StereoKitJNI.ui_settings_t_backplate_depth_get(swigCPtr, this);
  }

  public void setBackplate_border(float value) {
    StereoKitJNI.ui_settings_t_backplate_border_set(swigCPtr, this, value);
  }

  public float getBackplate_border() {
    return StereoKitJNI.ui_settings_t_backplate_border_get(swigCPtr, this);
  }

  public ui_settings_t() {
    this(StereoKitJNI.new_ui_settings_t(), true);
  }

}
