/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.stereokitbindings;

public class vec2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vec2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vec2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(vec2 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StereoKitJNI.delete_vec2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    StereoKitJNI.vec2_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return StereoKitJNI.vec2_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    StereoKitJNI.vec2_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return StereoKitJNI.vec2_y_get(swigCPtr, this);
  }

  public vec2() {
    this(StereoKitJNI.new_vec2(), true);
  }

}
